#!/bin/bash

sudo -v

# Enable parallell downloads with pacman
echo "ParallelDownloads = 5" >> /etc/pacman.conf

# Update the system
pacman -Syu

# This allows us to refresh sudo timeout
while :; do sudo -v; sleep 59; done &
# Remember to kill this at the end
infiloop=$!

cd "$HOME"
# Install yadm submodules, e.g. Emacs Config, org documents, zsh autocomplete etc.
yadm submodule update --recursive --init

# permissions
chmod 700 ~/.cache ~/.config
yadm checkout --quiet

# Install starship prompt
yes | sh -c "$(curl -fsSL https://starship.rs/install.sh)"

# Install some relevant applications
paru -S brave \
    postman-bin \
    bspwm xmonad feh flameshot polybar picom\
    xorg-xrdb xinit-xsession \
    python-pip --noconfirm

paru -S alacritty  --noconfirm
yes | pip install pywal qtile

# Install all the fonts we want
paru -Sy ttf-fira-code ttf-jetbrains-mono otf-overpass ttf-juliamono otf-ibm-plex ttf-merriweather ttf-alegreya --noconfirm

# PYTHON
pip install --user pipx

# I don't use pdm that much, but if PEP 582 gets accepted I might start to
# Anyway, it might be nice to have
pipx install pdm

# Install poetry
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

# Install pyenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
cd ~/.pyenv && sh setup-python.sh

# Install EPSON Printer drivers
paru -S epson-inkjet-printer-escpr --noconfirm

# Install some things for developments
paru -S npm
paru -S docker docker-compose

# EMACS
# Install this with paru for conveniance
paru -S libgccjit --noconfirm

# Here we need to edit the packagefile to enable JIT
git clone https://aur.archlinux.org/emacs-git.git
cd emacs-git
# Enable JIT compilation
sed -i 's/JIT=/JIT="YES"/g' PKGBUILD
makepkg -si --noconfirm

# Tangle our Emacs Config & install Doom Emacs
emacs --batch --eval "(progn (require 'org) (setq org-confirm-babel-evaluate nil) (org-babel-tangle-file \"~/.config/doom/config.org\"))"
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
yes | ~/.emacs.d/bin/doom install
yes |  ~/.config/doom/setup.sh

# Install LaTex and its utilities (should go pretty fast with parallel install)
paru -S texlive-most tllocalmgr-git --noconfirm


# Optional tethering support
paru -S libimobiledevice

# Kill sudo refresh
kill "$infiloop"
