#!/usr/bin/bash

# Get the current operating system
OS=$(uname -a)

# This allows us to refresh sudo timeout
while :; do sudo -v; sleep 59; done &
# Remember to kill this at the end
infiloop=$!

echo $OS
if [[ "$OS" == *"Ubuntu"* ]]; then
  echo "We are at Ubutu"
fi

# Install zsh if we haven't already
if [ ! $(command -v zsh) ]; then
    echo "Install zsh"
    if [[ "$OS" == *"Ubuntu"* ]]; then
        sudo apt install zsh -y
    elif [[ "$OS" == *"Arch"* || "$OS" == *"Manjaro"* ]]; then
        sudo pacman -S zsh --noconfirm
    fi
    chsh -s $(which zsh) # this will require a restart later
fi

# Install our defined yadm submodules, e.g. Emacs Config, org documents, zsh autocomplete etc.
yadm submodule update --recursive --init

# Update the systems package manager
if [[ "$OS" == *"Ubuntu"* ]]; then
    echo "We install some packages"
    sudo apt update
    sudo apt install unzip wget git curl apt-transport-https -y
elif [[ "$OS" == *"Arch"* || "$OS" == *"Manjaro"* ]]; then
    # Enable parallell downloads with pacman
    echo "ParallelDownloads = 5" >> /etc/pacman.conf
    pacman -Syu
    pacman -S --needed base-devel
    # Install paru to so we can use the AUR when installing
    git clone https://aur.archlinux.org/paru.git repos/ && cd repos/paru && makepkg -si
fi

# Change some permissions
chmod 700 ~/.cache ~/.config

# Get the working directory of the  bootstrap script
DIR="$(cd "$(dirname "$0")" && pwd)"

curl https://starship.rs/install.sh > /tmp/install.sh
sh /tmp/install.sh --force

# Setup our default shell environment with python
zsh $DIR/setup-python.sh

# Install the fonts we require
zsh $DIR/setup-fonts.sh

# Install some of the applications we needs
zsh $DIR/setup-apps.sh

# Install doom emacs
zsh $DIR/setup-emacs.sh

# Optional tethering support
if [[ "$OS" == *"Arch"* || "$OS" == *"Manjaro"* ]]; then
    paru -S libimobiledevice --noconfirm
fi

# Install EPSON Printer drivers, arch only
if [[ "$OS" == *"Arch"* || "$OS" == *"Manjaro"* ]]; then
    paru -S epson-inkjet-printer-escpr --noconfirm
fi

# Kill sudo refresh
kill "$infiloop"

# Ask the user if we shold logout
read -r -p "Want to logout for changes to take effect? [Y/n] " input
case $input in
    [yY][eE][sS]|[yY])
        pkill -f x
        ;;
    [nN][oO]|[nN])
        echo "Ok"
        ;;
    *)
    echo "Ok"
    exit 1
    ;;
esac
