# Get the current operating system
OS=$(uname -a)

# Installing Emacs
if [[ "$OS" == *"Ubuntu"* ]]; then
    sudo apt install libtool libtool-bin cmake -y # For building vterm in Emacs
    sudo apt install snapd -y
    sudo snap install emacs --classic
elif [[ "$OS" == *"Arch"* || "$OS" == *"MANJARO"* ]]; then
    sudo pacman -S cmake emacs --noconfirm

    # Install this with paru for conveniance    
    # paru -S libgccjit cmake --noconfirm

    # Here we need to edit the packagefile to enable JIT
    # mkdir repos
    # git clone https://aur.archlinux.org/emacs-git.git repos

    # Build emacs
    # cd repos/emacs-git && sed -i 's/JIT=/JIT="YES"/g' PKGBUILD && makepgk -si --noconfirm
elif [[ "$OS" == *"Darwin"* ]]; then
    brew tap d12frosted/emacs-plus
    brew install emacs-plus@29
    brew install cmake # For building vterm
fi

# Tangle our Emacs Config & install Doom Emacs
emacs --batch --eval "(progn (require 'org) (setq org-confirm-babel-evaluate nil) (org-babel-tangle-file \"~/.config/doom/config.org\"))"
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
# yes |  bash $HOME/.config/doom/setup.sh
yes | ~/.emacs.d/bin/doom install

# Apply the current emacs theme to the entire system using wal
emacs --eval "(progn (theme-magic-from-emacs) (kill-emacs))" && cp ~/.cache/wal/colors.Xresources ~/.Xresources && xrdb ~/.Xresources
# Create a soft link to the wal theme generated by rofi
ln -s $HOME/.cache/wal/rofiWalTheme.rasi $HOME/.config/rofi/rofiWalTheme.rasi

if [[ "$OSTYPE" == "linux-gnu"*  && -f .config/systemctl/user/emacs.service ]]; then
    # Start emacs as a service on systems with systemd
    systemctl enable --user emacs
    systemctl start --user emacs
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Enable emacs as background service on MAC OS
    LaunchString='<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>Label</key>
        <string>gnu.emacs.daemon</string>
        <key>ProgramArguments</key>
        <array>
        <string>PATH-TO-EMACS</string>
        <string>--daemon</string>
        </array>
    <key>RunAtLoad</key>
    <true/>
    <key>ServiceDescription</key>
    <string>Gnu Emacs Daemon</string>
    </dict>
    </plist>'
    echo "${LaunchString/PATH-TO-EMACS/$(which emacs)}" >> ~/Library/LaunchAgents/gnu.emacs.daemon.plist
    launchctl load -w ~/Library/LaunchAgents/gnu.emacs.daemon.plist
fi
